/* CPU-only SDMA scheduling model. Compile with the extracted production
 * worker header generated by test_rocm_stream_pipeline.py. */
#include <assert.h>
#include <errno.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define DS4_GPU_LOG_PREFIX "test: "
#define cudaSuccess 0
#define cudaMemcpyHostToDevice 1
#define DS4_ROCM_STREAM_READ_WORKERS 4
#define JOB_BYTES 64

typedef int cudaError_t;
typedef struct {
    char *dst;
    uint64_t offset, bytes;
    void *host_raw, *host_buf;
    int ok, uploaded, errnum, direct;
} cuda_stream_read_job;
typedef struct {
    void *dst;
    const void *src;
    size_t bytes;
    int failure;
} mock_stream;
typedef mock_stream *cudaStream_t;

static pthread_mutex_t g_stream_read_mutex = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t g_stream_read_work_cond = PTHREAD_COND_INITIALIZER;
static pthread_cond_t g_stream_read_done_cond = PTHREAD_COND_INITIALIZER;
static int g_stream_read_pool_stop, g_stream_read_active_ok;
static cuda_stream_read_job *g_stream_read_active_jobs;
static uint32_t g_stream_read_active_count, g_stream_read_active_next, g_stream_read_active_done;
static void *g_stream_read_stage_raw[4];
static uint64_t g_stream_read_stage_bytes[4];
static cudaStream_t g_stream_read_upload_streams[4];
static int g_stream_read_profile_enabled;
static uint64_t g_stream_read_profile_jobs, g_stream_read_profile_bytes;
static uint64_t g_stream_read_profile_read_us, g_stream_read_profile_upload_us;
static int read_failure;

static double cuda_wall_sec(void) {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return t.tv_sec + t.tv_nsec / 1e9;
}
static uint64_t cuda_stream_read_profile_us(double t) { return (uint64_t)(t * 1e6); }
static int cudaSetDevice(int dev) { return dev; }
static int cudaGetLastError(void) { return 0; }
static const char *cudaGetErrorString(int err) { (void)err; return "injected failure"; }
static void cuda_model_drop_file_pages(uint64_t off, uint64_t bytes) { (void)off; (void)bytes; }

static cudaError_t cudaMemcpyAsync(void *dst, const void *src, size_t bytes,
                                   int kind, cudaStream_t stream) {
    (void)kind;
    assert(!stream->src); /* at most one pending upload per worker */
    if (stream->failure == 1) return 1;
    stream->src = src;
    stream->dst = dst;
    stream->bytes = bytes;
    return 0;
}
static cudaError_t cudaStreamSynchronize(cudaStream_t stream) {
    /* Deliberately defer the source read until synchronization. Reusing a
     * staging bank too early corrupts the destination and fails the test. */
    if (stream->src) memcpy(stream->dst, stream->src, stream->bytes);
    stream->src = NULL;
    return stream->failure == 2 ? 1 : 0;
}
static void cuda_stream_read_job_run(cuda_stream_read_job *job, void *stage, uint64_t capacity) {
    assert(capacity >= job->bytes);
    job->ok = 0;
    job->uploaded = 0;
    if (read_failure && job->offset == 3) { job->errnum = EIO; return; }
    memset(stage, (int)job->offset, job->bytes);
    job->host_raw = job->host_buf = stage;
    job->ok = 1;
}

/* Disabled trace hooks must not change the worker's completion protocol. */
static uint32_t rocm_trace_cpu_begin(const char *name, uint64_t lane, uint64_t bytes) {
    (void)name; (void)lane; (void)bytes; return 0;
}
static void rocm_trace_cpu_end(uint32_t id, int ok) { (void)id; (void)ok; }
static uint32_t rocm_trace_upload_begin(cudaStream_t stream, uint64_t bytes) {
    (void)stream; (void)bytes; return 0;
}
static void rocm_trace_upload_end(uint32_t id, cudaStream_t stream, int ok) {
    (void)id; (void)stream; (void)ok;
}

#include "ds4_stream_pipeline_under_test.h"

static void run_case(unsigned count, unsigned workers, int failure, int profile) {
    cuda_stream_read_job jobs[257] = {{0}};
    char dst[257][JOB_BYTES] = {{0}};
    char stage[4][2 * JOB_BYTES];
    mock_stream streams[4] = {{0}};
    pthread_t threads[4];
    uint32_t ids[4];
    assert(count <= 257);
    read_failure = failure == 3;
    g_stream_read_profile_enabled = profile;
    g_stream_read_pool_stop = 0;
    g_stream_read_active_jobs = jobs;
    g_stream_read_active_count = count;
    g_stream_read_active_next = g_stream_read_active_done = 0;
    g_stream_read_active_ok = 1;
    for (unsigned i = 0; i < count; i++) {
        jobs[i].dst = dst[i];
        jobs[i].offset = i % 251 + 1;
        jobs[i].bytes = JOB_BYTES;
    }
    for (unsigned i = 0; i < workers; i++) {
        streams[i].failure = failure == 3 ? 0 : failure;
        g_stream_read_upload_streams[i] = &streams[i];
        g_stream_read_stage_raw[i] = stage[i];
        g_stream_read_stage_bytes[i] = JOB_BYTES;
        ids[i] = i;
        assert(pthread_create(&threads[i], NULL, cuda_stream_read_pipeline_worker, &ids[i]) == 0);
    }
    pthread_mutex_lock(&g_stream_read_mutex);
    while (g_stream_read_active_done != count) {
        pthread_cond_wait(&g_stream_read_done_cond, &g_stream_read_mutex);
    }
    assert(g_stream_read_active_ok == (failure == 0));
    g_stream_read_pool_stop = 1;
    pthread_cond_broadcast(&g_stream_read_work_cond);
    pthread_mutex_unlock(&g_stream_read_mutex);
    for (unsigned i = 0; i < workers; i++) {
        pthread_join(threads[i], NULL);
        assert(!streams[i].src);
    }
    for (unsigned i = 0; i < count; i++) {
        const int failed = failure == 1 || failure == 2 || (failure == 3 && jobs[i].offset == 3);
        assert(jobs[i].ok == !failed);
        assert(jobs[i].uploaded == !failed);
        if (!failed) {
            for (unsigned j = 0; j < JOB_BYTES; j++) assert((unsigned char)dst[i][j] == jobs[i].offset);
        }
    }
}

int main(void) {
    const unsigned counts[] = {1, 2, 3, 17, 257};
    for (unsigned w = 1; w <= 4; w++) {
        for (unsigned c = 0; c < sizeof(counts) / sizeof(counts[0]); c++) {
            for (unsigned repeat = 0; repeat < 10; repeat++) run_case(counts[c], w, 0, repeat % 2);
        }
        for (int failure = 1; failure <= 3; failure++) run_case(17, w, failure, 1);
    }
    puts("ROCm pipeline staging, completion and error tests: PASS");
    return 0;
}
